name: strawberry
channels:
  - openalea3
  - conda-forge

dependencies:
 - python
 - pandas 
 - k3d 
 - jupyter 
 - nodejs 
 - cufflinks-py 
 - ipyvuetify 
 - plotly
 - openalea.deploy 
 - openalea.mtg 
 - openalea.plantgl 
 - openpyxl
 - openalea.lpy
 - pyvis
 - voila
 - voila-vuetify
