{% set data = load_setup_py_data() %}

package:
  name: openalea.strawberry
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python  {{PY_VER}}
    - openalea.deploy
  run:
    - python >=3.6
    - openalea.deploy
    - openalea.plantgl
    - openalea.mtg
    - oawidgets
    - pandas
    - jupyter 
    - voila 
    - voila-vuetify 
    - nodejs 
    - cufflinks-py 
    - ipyvuetify 
    - plotly
    - matplotlib


test:
  requires:
    - pytest
  imports:
    - openalea.strawberry
  source_files:
    - share/data/**
    - test/**
  commands:
    - cd test
    - pytest -v 

about:
  home: http://strawberry.rtfd.io
  license: CeCILL_C
  summary: Strawberry plant architecture analysis and 2D/3D reconstruction.

