{% set version = "1.0.0" %}

package:
  name: openalea.strawberry
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - openalea.deploy #==2.0.0
  run:
    - python
    - openalea.mtg
    - openalea.plantgl
    - pandas
    - k3d 
    - jupyter 
    - voila 
    - voila-vuetify 
    - nodejs 
    - cufflinks-py 
    - ipyvuetify 
    - qgrid 
    - plotly
    - openalea.deploy 
    - openalea.mtg 
    - openalea.plantgl 
    - openalea.lpy
    - pyvis
    - pgljupyter

test:
  imports:
    - openalea.strawberry
  source_files:
    - test/
    - test/*.py

  commands:
    - pytest

about:
  home: http://github.com/openalea/strawberry
  license: Cecill-c License
  summary: OpenAlea Strawberry is a package for architecture analysis and 2D/3D reconstruction.

