name: strawberry
channels:
  - openalea3
  - conda-forge
  - nodefaults

dependencies:
  - python
  - sphinx_rtd_theme
  - readthedocs-sphinx-ext
  - openalea.strawberry
  - nbsphinx
  - nbsphinx-link
