name: strawberry
channels:
  - openalea3
  - conda-forge

dependencies:
  - python
  - sphinx_rtd_theme
  - readthedocs-sphinx-ext
  - openalea.strawberry
  - nbsphinx
  - nbsphinx-link
  - python
  - pandas 
  - k3d 
  - jupyter 
  - nodejs 
  - cufflinks-py 
  - ipyvuetify 
  - plotly
  - openalea.deploy 
  - openalea.mtg 
  - openalea.plantgl 
  - openpyxl
  - openalea.lpy
  - pyvis
  - voila
  - voila-vuetify
  - pip
  - pip:
    - -e ..
